name: Homelab Online Hosts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * 1,2,3,4,5'

jobs:
  Homelab-Hosts:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Script
      run: |

        subnet="10.0.30."
        for i in {1..254}; do
          ip="${subnet}${i}"

          ping -c 1 -W 1 $ip > /dev/null 2>&1

          if [ $? -eq 0 ]; then
            echo $ip is online
            echo $ip >> online.txt
          fi
        done

    - name: Commit changes
      run: |
            git config --local user.email "hakrishi@pm.me"
            git config --local user.name "hakrishi"
            git add .
            git commit -m "online hosts update" -a || true
            git push
      